name: lgbm-classifier
type: training
targetType: binary
environmentID: null
# modelID: optional
#trainingModel:
#  trainOnProject: optional project on which to train
validation:
  # Path is relative to this file
  input: ../data/loss_cost_demo.csv
  targetName: IncurredClaims
majorVersion: True
targetName: is_bad
positiveClassLabel: 1
negativeClassLabel: 0
predictionThreshold: 0.17
language: Python
description: null
id: null
versionId: null
trainingData: ../data/loss_cost_demo.csv
modelVersionID: null
