description: null
language: Python
majorVersion: true
name: lgbm-classifier
negativeClassLabel: 0
positiveClassLabel: 1
predictionThreshold: 0.17
targetName: is_bad
targetType: binary
testData: /Users/timothy.whittaker/Desktop/git/ford-mlops/data/10K_LC_short.csv
trainingData: /Users/timothy.whittaker/Desktop/git/ford-mlops/data/10K_Lending_Club_Loans_utf-8.csv
type: inference
versionId: null
