name: lgbm-regression
type: training
targetType: regression
environmentID: null
# modelID: optional
#trainingModel:
#  trainOnProject: optional project on which to train
validation:
  # Path is relative to this file
  input: ../data/loss_cost_demo.csv
  targetName: IncurredClaims
majorVersion: True
targetName: IncurredClaims
positiveClassLabel: null
negativeClassLabel: null
predictionThreshold: null
language: Python
description: null
id: null
versionId: null
trainingData: ../data/loss_cost_demo.csv
modelVersionID: null
